# Generated by Django 4.1 on 2023-08-08 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="post_category",
                to="blog.category",
                verbose_name="categories",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="date"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="post_images", verbose_name="image"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.TextField(max_length=255, verbose_name="title"),
        ),
    ]
