# Generated by Django 4.1 on 2023-07-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="about/")),
                ("what_we_do", models.TextField(max_length=1000)),
                ("our_mission", models.TextField(max_length=1000)),
                ("our_goal", models.TextField(max_length=1000)),
                ("why_you_choose_us", models.TextField(max_length=1000)),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "Abouts",
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
            ],
            options={
                "verbose_name": "Faq",
                "verbose_name_plural": "Faqs",
            },
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("logo", models.ImageField(upload_to="info/")),
                ("descrpition", models.TextField(max_length=1000)),
                ("address", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=30)),
                ("fb_url", models.URLField()),
                ("tw_url", models.URLField()),
                ("in_url", models.URLField()),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Info",
                "verbose_name_plural": "Infos",
            },
        ),
    ]
