# Generated by Django 4.1 on 2023-08-01 04:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="name",
            new_name="site_name",
        ),
    ]
