# Generated by Django 4.1 on 2023-08-01 05:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_rename_name_info_site_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="descrpition",
            new_name="description",
        ),
    ]
