# Generated by Django 4.1 on 2023-07-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0002_property_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(max_length=2000),
        ),
    ]
