# Generated by Django 4.1 on 2023-07-31 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0003_alter_property_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyreservation",
            name="date_from",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="propertyreservation",
            name="date_to",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
