# Generated by Django 4.1 on 2023-08-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0004_alter_propertyreservation_date_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(default="", max_length=255),
        ),
    ]
